dvh_fam_fp_dbt:
  target: "{{env_var('DBT_DB_TARGET')}}"
  outputs:
    U:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dmv34-scan.adeo.no
      port: 1521
      service: ccdwhu1_ha
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
  session_info:
    client_info: "{{env_var('DBT_ORCL_USER_PROXY', 'DVH_FAM_DBT')}}"
    module: "{{env_var('AIRFLOW_DAG_ID', 'dvh_fam_fp_dbt')}}"
    action: "Kjører utpakking av foreldrepenger data"
    R:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dmv34-scan.adeo.no
      port: 1521
      service: dwhr_ha
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
  session_info:
    client_info: "{{env_var('DBT_ORCL_USER_PROXY', 'DVH_FAM_DBT')}}"
    module: "{{env_var('AIRFLOW_DAG_ID', 'dvh_fam_fp_dbt')}}"
    action: "Kjører utpakking av foreldrepenger data"
    P:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dmv09-scan.adeo.no
      port: 1521
      service: dwh_ha
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
  session_info:
    client_info: "{{env_var('DBT_ORCL_USER_PROXY', 'DVH_FAM_DBT')}}"
    module: "{{env_var('AIRFLOW_DAG_ID', 'dvh_fam_fp_dbt')}}"
    action: "Kjører utpakking av foreldrepenger data"
config:
  send_anonymous_usage_stats: False